module.exports.obter = require('./obter')
module.exports.obterPorProjeto = require('./obter-projeto')
module.exports.cadastrar = require('./cadastrar')
module.exports.editar = require('./editar')
module.exports.remover = require('./remover')