module.exports.obter = require('./obter')
module.exports.obterTodos = require('./obter-todos')
module.exports.cadastrar = require('./cadastrar')
module.exports.editar = require('./editar')
module.exports.remover = require('./remover')
module.exports.alterarPosicao = require('./alterar-posicao')