module.exports.obter = require('./obter')
module.exports.obterTodos = require('./obter-todos')
module.exports.cadastrar = require('./cadastrar')
module.exports.editar = require('./editar')
module.exports.migrar = require('./migrar')
module.exports.transmitir = require('./transmitir')
module.exports.remover = require('./remover')