module.exports.obter = require('./obter')
module.exports.obterTodos = require('./obter-todos')
module.exports.cadastrar = require('./cadastrar')
module.exports.editar = require('./editar')
module.exports.remover = require('./remover')
module.exports.obterImagem = require('./obter-imagem')
module.exports.inserirImagem = require('./inserir-imagem')
module.exports.removerImagem = require('./remover-imagem')